### ISSUE TITLE
Error when running catklin_make

### ISSUE THREAD

**Issue by ximenesfel** [stevenjj/openpose_ros#10]
Hi,

I tried to install openpose_ros on my laptop but the bellow is slowed when I tried to use catklin_make:

**Environment configuration:**
Ubuntu 16.04
CUDA 8.0
CUDNN 5.1
Opencv 3.2.0
PCL 1.8
Openpose ( Tested and working corrected)
Ros kinetic (Tested and working corrected)
GPU: GTX 1060

`Base path: /home/ximenes/catkin_ws
Source space: /home/ximenes/catkin_ws/src
Build space: /home/ximenes/catkin_ws/build
Devel space: /home/ximenes/catkin_ws/devel
Install space: /home/ximenes/catkin_ws/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/ximenes/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/kinetic
-- This workspace overlays: /opt/ros/kinetic
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/ximenes/catkin_ws/build/test_results
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.11
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 4 packages in topological order:
-- ~~  - robot
-- ~~  - openpose_ros_msgs
-- ~~  - openpose_ros_pkg
-- ~~  - skeleton_extract_3d
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'robot'
-- ==> add_subdirectory(robot)
-- +++ processing catkin package: 'openpose_ros_msgs'
-- ==> add_subdirectory(openpose_ros/openpose_ros_msgs)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- openpose_ros_msgs: 4 messages, 1 services
-- +++ processing catkin package: 'openpose_ros_pkg'
-- ==> add_subdirectory(openpose_ros/openpose_ros_pkg)
-- +++ processing catkin package: 'skeleton_extract_3d'
-- ==> add_subdirectory(openpose_ros/skeleton_extract_3d)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   iostreams
--   serialization
--   chrono
--   atomic
--   regex
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

-- looking for PCL_COMMON
-- looking for PCL_KDTREE
-- looking for PCL_OCTREE
-- looking for PCL_SEARCH
-- looking for PCL_IO
-- looking for PCL_SAMPLE_CONSENSUS
-- looking for PCL_FILTERS
-- looking for PCL_GEOMETRY
-- looking for PCL_FEATURES
-- looking for PCL_SEGMENTATION
-- looking for PCL_SURFACE
-- looking for PCL_REGISTRATION
-- looking for PCL_RECOGNITION
-- looking for PCL_KEYPOINTS
-- looking for PCL_VISUALIZATION
-- looking for PCL_PEOPLE
-- looking for PCL_OUTOFCORE
-- looking for PCL_TRACKING
-- looking for PCL_APPS
-- Could NOT find PCL_APPS (missing:  PCL_APPS_LIBRARY) 
-- looking for PCL_MODELER
-- looking for PCL_IN_HAND_SCANNER
-- looking for PCL_POINT_CLOUD_EDITOR
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CAFFE_LIBRARY
    linked by target "openpose_ros_node_firephinx" in directory /home/ximenes/catkin_ws/src/openpose_ros/openpose_ros_pkg
    linked by target "openpose_ros" in directory /home/ximenes/catkin_ws/src/openpose_ros/openpose_ros_pkg
    linked by target "openpose_ros_node_3d" in directory /home/ximenes/catkin_ws/src/openpose_ros/openpose_ros_pkg
    linked by target "openpose_ros_node" in directory /home/ximenes/catkin_ws/src/openpose_ros/openpose_ros_pkg
OPENPOSE_LIBRARY
    linked by target "openpose_ros_node_firephinx" in directory /home/ximenes/catkin_ws/src/openpose_ros/openpose_ros_pkg
    linked by target "openpose_ros" in directory /home/ximenes/catkin_ws/src/openpose_ros/openpose_ros_pkg
    linked by target "openpose_ros_node_3d" in directory /home/ximenes/catkin_ws/src/openpose_ros/openpose_ros_pkg
    linked by target "openpose_ros_node" in directory /home/ximenes/catkin_ws/src/openpose_ros/openpose_ros_pkg

-- Configuring incomplete, errors occurred!
See also "/home/ximenes/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/ximenes/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed'

Can you help me with this issue? If need more information, please let me know.

Best regards,
Felipe Ximenes

**Comment by angelbeibei** [comment]
@ximenesfel Have you compiled successfully? thanks.

**Comment by stevenjj** [comment]
It seems that this one cannot find the Caffe library. It's hard-coded in the CMakeLists.txt but you can change it to point to the correct .so file in your environment. A lot has changed since 14.04.
