### ISSUE TITLE
Error when running catklin_make

### ISSUE THREAD

**Issue by angelbeibei** [stevenjj/openpose_ros#13]
HI!
I tried to use catkin_make,but i met this error.
who can hlep me?? Thanks

/usr/bin/ld: CMakeFiles/openpose_ros_node_firephinx.dir/src/openpose_ros_node_firephinx.cpp.o: undefined reference to symbol '_ZN2cv7waitKeyEi'
//usr/local/lib/libopencv_highgui.so.2.4: error adding symbols: DSO missing from command line

**Comment by senguptaa** [comment]
@angelbeibei How did you fix this issue? I see the same error on my side

**Comment by angelbeibei** [comment]
@senguptaa 
Sorry, I've forgotten how to solve this problem. Although the final installation was successful, the final speed was very slow, so I gave up this.
