### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by angelbeibei** [stevenjj/openpose_ros#14]
HI
when i run 
roslaunch skeleton_extract_3d openpose_skeleton_extract.launch
 I met this error, can you help me? thanks

[ERROR] [1538191977.569161132]: Failed to call service detect_poses_3d
[ERROR] [1538191977.569219004]: Did you remap the service and client names?
[ERROR] [1538191977.569261286]: This node expects a service called skeleton_2d_detector in which a launch file should have handled the remapping

**Comment by SilentLancer** [comment]
What the solution you did to fix this?

**Comment by angelbeibei** [comment]
@SilentLancer 
sorry，I did not solve this problem, then I will not use this project anymore.
