### ISSUE TITLE
Caffe Library variable not found on building openpose_ros_pkg

### ISSUE THREAD

**Issue by Harsharma2308** [stevenjj/openpose_ros#16]
I am getting the following error-
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CAFFE_LIBRARY

```
Do I need to set it up explicitly? I have caffe built.

**Comment by stevenjj** [comment]
Hi. Try changing this CMake variable to point to the location of caffe's .so file.
```
FIND_LIBRARY(CAFFE_LIBRARY caffe ../openpose/3rdparty/caffe/distribute/lib)
```
https://github.com/stevenjj/openpose_ros/blob/master/openpose_ros_pkg/CMakeLists.txt#L53

**Comment by Harsharma2308** [comment]
I changed it to this-
`FIND_LIBRARY(CAFFE_LIBRARY caffe ../openpose/3rdparty/caffe/build/lib`
It works now. Thanks
