### ISSUE TITLE
skeleton_extract_3d planned work

### ISSUE THREAD

**Issue by MiguelARD** [stevenjj/openpose_ros#3]
I had a look at the skeleton_extract_3d_node and its planned work and it looks amazing. I am very interested in your work and it would be incredible to have that node working. Are you planning to release the node completed soon?

Thanks in advanced.

**Comment by stevenjj** [comment]
I'm currently busy with another part of my project, so I won't have time to fully complete the node. Some functionality may be present, but I don't think it will meet your needs.

But, you are free to work on it and make a pull request to share your contributions. :)

**Comment by MiguelARD** [comment]
I am a newbie and I am not sure if I will be able but I will try to complete it and if I succed I will make the pull request ;) .

**Comment by Harsharma2308** [comment]
Hi, Is this thing done?
It would be really hepful to me if this is done.

**Comment by stevenjj** [comment]
Hey @Harsharma2308 . It's been done by @MiguelARD  with this pull request https://github.com/stevenjj/openpose_ros/pull/4 The code right now has that implementation.

However, the current implementation outputs the 3d locations at a few Hz. I haven't found the time to improve the speed.

**Comment by Harsharma2308** [comment]
Thanks
