### ISSUE TITLE
Skeletons works not well.

### ISSUE THREAD

**Issue by pyni** [stevenjj/openpose_ros#5]
Hi, i use your code, but when i use skeleton node , this effect is shown as follows:
![default](https://user-images.githubusercontent.com/18031767/32205302-71eed170-be29-11e7-9f51-a1b9706c6074.png)
The rgb works well , but the skeletons are in a mess

**Comment by pyni** [comment]
i use xtion camera and openni driver
the settings are like this:
![default](https://user-images.githubusercontent.com/18031767/32205352-aff53b58-be29-11e7-8264-3d6febdb76c5.png)
Both rgb and depth are 640 X 480
So could you please give me some advices?

**Comment by stevenjj** [comment]
Hi. Your 2D detection seems to not have the correct resolution.
Did you change the resolution values in `openpose_ros_pkg/src/openpose_ros_node_firephinx.cpp` 
````
#define OUTPUT_RES_X 1280 // Display Resolution Output Width
#define OUTPUT_RES_Y 720  // Display Resolution Output Height
````
and `skeleton_extract_3d/src/skeleton_extract_3d_node.cpp` 
````
#define width  960
#define height 540
````
?
If not, try changing them to
````
#define OUTPUT_RES_X 640 // Display Resolution Output Width
#define OUTPUT_RES_Y 480  // Display Resolution Output Height
````
and
````
#define width  640
#define height 480
````
respectively. These values must match your camera's resolution.

**Comment by pyni** [comment]
![default](https://user-images.githubusercontent.com/18031767/32304693-27f489f0-bfac-11e7-8367-8fccee6577c1.png)

Yeah, i find it.
it is in openpsoe_ros_node_3d.cpp
  output_size.x = getParam(local_nh, "output_width", 640);
  output_size.y = getParam(local_nh, "output_height", 480);
Thanks for your code!
